package com.wolfewinters.assignment03;
import com.wolfewinters.assignment03.Recipe;
import java.util.LinkedList;
public class DataProvider {
    static LinkedList<Recipe> recipes;
    static LinkedList<Recipe> getRecipes() {return recipes;}
    static {
        recipes = new LinkedList<Recipe>();
        String name = "Bread Machine Bagels";
        String description = "Quick and easy bagels you can make with your bread machine! You can use whatever topping that you wish, many like poppy seeds";
        String image = "https://www.allrecipes.com/recipe/7178/bread-machine-bagels/photos/5993392/";
        String ingredients = "1 cup warm water (110 degrees F/45 degrees C)1 1/2 teaspoons salt2 tablespoons white sugar3 cups bread flour2 1/4 teaspoons active dry yeast3 quarts boiling water3 tablespoons white sugar1 tablespoon cornmeal1 egg white3 tablespoons poppy seeds";
        String directions = "Place water, salt, sugar, flour and yeast in the bread machine pan in the order recommended by the manufacturer. Select Dough setting.When cycle is complete, let dough rest on a lightly floured surface. Meanwhile, in a large pot bring 3 quarts of water to a boil. Stir in 3 tablespoons of sugar.Cut dough into 9 equal pieces, and roll each piece into a small ball. Flatten balls. Poke a hole in the middle of each with your thumb. Twirl the dough on your finger or thumb to enlarge the hole, and to even out the dough around the hole. Cover bagels with a clean cloth, and let rest for 10 minutes.Sprinkle an ungreased baking sheet with cornmeal. Carefully transfer bagels to boiling water. Boil for 1 minute, turning half way through. Drain briefly on clean towel. Arrange boiled bagels on baking sheet. Glaze tops with egg white, and sprinkle with your choice of toppings.Bake in a preheated 375 degree F (190 degrees C) oven for 20 to 25 minutes, until well browned.";
        recipes.add(new Recipe(name, description, image, ingredients, directions));
        name = "San Francisco Style Bagels";
        description = "I accidentally stumbled upon a method for making bagels that were structurally and texturally superior, I decided to take advantage of that fact, and the San Francisco-style bagel was born.";
        image = "https://www.allrecipes.com/recipe/228643/san-francisco-style-bagels/photos/1109900/";
        ingredients = "1 pound bread flour, divided in half1 1/2 teaspoons active dry yeast1 1/4 cups warm water1 1/2 teaspoons salt1 teaspoon cornmeal, or as needed4 cups water1 tablespoon salt2 teaspoons honey1 egg, beaten1 tablespoon sesame seeds, or more if desired";
        directions = "Combine half the flour, yeast, and warm water in the bowl of a stand mixer. Cover and set aside at room temperature until doubled in size, about 30 minutes.Stir in 1 1/2 teaspoons salt and the other half of the flour into the flour-water mixture. Knead with the dough hook of the stand mixer until it forms into a smooth, elastic ball that pulls away from the sides, about 10 minutes.Flour your hands, remove the dough and gently form it into a ball. Place back in the bowl, cover and let rise in a warm place until doubled in size, about 1 hour 15 minutes.Divide dough into 8 equally-sized pieces, about 3 ounces each. Form each piece into a ball and poke a hole in the center, stretching to create an open and even-sized hole. Place on a floured surface, sprinkle with additional flour, cover with plastic, and let rest for 30 minutes.Preheat oven to 400 degrees F (200 degrees C). Sprinkle a baking sheet with cornmeal.Bring 4 cups water, 1 tablespoon salt, and 2 teaspoons honey to a boil in a wide, deep pan. Working in batches, boil 2 to 3 bagels for 2 minutes per side. Transfer to a wire rack to drain.Place bagels on the prepared baking sheet. Brush with beaten egg and sprinkle with sesame seeds. Bake in the preheated oven until golden and cooked inside, 25 to 30 minutes.";
        recipes.add(new Recipe(name, description, image, ingredients, directions));
        name = "Pumpernickel Bagels";
        description = "Hearty dark rye bagels can be made at home. Rye flour, cocoa, coffee, and caraway seeds make these taste so good!";
        image = "https://images.media-allrecipes.com/userphotos/125x70/4557069.jpg";
        ingredients = "1 1/4 cups warm water1 cup whole-wheat flour4 teaspoons active dry yeast1 cup rye flour1/2 cup molasses1/3 cup unsweetened cocoa powder1 tablespoon vegetable oil1 tablespoon instant coffee granules1 tablespoon caraway seeds1 1/2 teaspoons salt1 1/4 cups all-purpose flour1 gallon water";
        directions = "Combine warm water, whole-wheat flour, and yeast in a small bowl. Let stand until the yeast softens and begins to froth and bubble, about 10 minutes.Mix rye flour, molasses, cocoa powder, vegetable oil, coffee granules, caraway seeds, and salt in a large bowl. Add yeast mixture and all-purpose flour. Turn dough onto a floured surface; knead until smooth and elastic, about 10 minutes. Grease a large bowl.Transfer dough to greased bowl; cover with warm damp towel or plastic wrap. Let rise in a warm area until doubled in size, about 1 hour.Preheat an oven to 450 degrees F (230 degrees C). Grease a baking sheet.Bring water to a boil in a large pot. Divide dough into 13 pieces; shape into balls. Press a hole into the center of each dough ball; pull dough to form a 1-inch hole in the center, keeping dough about 1/2-inch thick. Drop dough circles into boiling water, 3 or 4 at a time. Boil each side for 45 seconds. Remove with a slotted spoon and drain for about 1 minute. Arrange boiled bagels on prepared baking sheet.Bake bagels in the preheated oven until just starting to brown on the bottom, 8 to 10 minutes.";
        recipes.add(new Recipe(name, description, image, ingredients, directions));
    }
}